# Generated by Django 5.0.2 on 2024-03-14 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_last_name', models.CharField(max_length=50)),
                ('employee_first_name', models.CharField(max_length=50)),
                ('employee_date_of_birth', models.DateField()),
                ('employee_gender', models.CharField(max_length=10)),
                ('employee_phone', models.CharField(max_length=20)),
                ('employee_email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('employee_role_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('employee_role_title', models.CharField(max_length=50)),
                ('employee_role_description', models.TextField()),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('guest_title', models.CharField(max_length=10)),
                ('guest_first_name', models.CharField(max_length=50)),
                ('guest_last_name', models.CharField(max_length=50)),
                ('guest_date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('guest_phone_number', models.CharField(max_length=20)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_address', models.CharField(max_length=50)),
                ('guest_city', models.CharField(max_length=50)),
                ('guest_state', models.CharField(max_length=50)),
                ('guest_country', models.CharField(max_length=50)),
                ('guest_postcode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'guest',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hotel_address', models.CharField(max_length=50)),
                ('hotel_city', models.CharField(max_length=50)),
                ('hotel_country', models.CharField(max_length=50)),
                ('hotel_postcode', models.CharField(max_length=50)),
                ('hotel_phone_number', models.CharField(max_length=20)),
                ('hotel_star_rating', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_card_number', models.TextField()),
                ('payment_card_expiry_date', models.DateField()),
                ('payment_for_booking', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_for_service', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_for_bar', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_for_late_check_out', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_for_miscellaneous', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_for_miscellaneous_description', models.TextField()),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('room_type_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('room_type_description', models.TextField()),
                ('room_type_images', models.FileField(upload_to='')),
                ('room_type_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'room_type',
            },
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_cost',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_check_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_check_out',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_made_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_number_of_adults',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_number_of_children',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_special_requests',
            field=models.TextField(default=str),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='booking',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='room_booking',
                                    to='hotel_booking_app.booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_status',
            field=models.CharField(default=str, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings',
                                    to='hotel_booking_app.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(related_name='employees', to='hotel_booking_app.employee_role'),
        ),
        migrations.AddField(
            model_name='guest',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_booking',
                                    to='hotel_booking_app.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='guest_bookings', to='hotel_booking_app.guest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='guest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE,
                                    to='hotel_booking_app.guest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_booking_app.hotel'),
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE,
                                    to='hotel_booking_app.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_booking',
                                    to='hotel_booking_app.booking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_guest',
                                    to='hotel_booking_app.guest'),
        ),
        migrations.AddField(
            model_name='guest',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_payment',
                                    to='hotel_booking_app.payment'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='payment_bookings', to='hotel_booking_app.payment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_booking_app.room_type'),
        ),
    ]
